### PR TITLE
Fix pull-platformplatform-changes CLI command on Windows

### LINKED ISSUE #654: The CLI command `pull-platform-changes` fails on Windows
### Detailed description?

**Describe the bug**
On Windows, when running `pp pull-platform-changes`, during the test phase, it fails while trying to build with npm:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'npm' with working directory 'C:\Projects\GitHub\platformplatform\PlatformPlatform\application'. The system cannot find the file specified.
```

**Expected behavior**
To have the npm build started.

**Additional context**
This only occurs on Windows machines as npm is not an executable but a command script.

### Severity

Medium

### Is this bug security related?

- [ ] This bug is related to security

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by thiagolunardi**
### Summary & Motivation

While running on Windows, the `pp pull-platform platform-changes` fails because it couldn't find the `npm` command, which is not an executable file.

This fix searches for the precise command location while running on Windows OS using the `.exe` and `.cmd` extensions.

### Checklist

- [x] I have added tests, and done manual regression tests
- [x] I have updated the documentation, if necessary

### CODE REVIEW

File: developer-cli/Utilities/ProcessHelper.cs [hunk 1]
```diff
@@ -123,6 +124,29 @@ public static bool IsProcessRunning(string process)
...
     }
+
+    private static string? FindFullPathFromPath(string command)
+    {
+        Debug.Assert(!string.IsNullOrWhiteSpace(command));
+
+        string[] commandFormats = OperatingSystem.IsWindows() ? ["{0}.exe", "{0}.cmd"] : ["{0}"];
+
+        var pathVariable = Environment.GetEnvironmentVariable("PATH");
+        foreach (var directory in pathVariable?.Split(';') ?? [])
```
Comment (tjementum) [inline developer-cli/Utilities/ProcessHelper.cs:135]: @thiagolunardi The logic here here fails because on Mac and Linux `:` is used as path separator and not `;`.

I've tried this code and it seems to work... but I have to test that this did not break any other tings:

```C#
var pathVariable = Environment.GetEnvironmentVariable("PATH");
if (pathVariable == null) return null;

var separator = OperatingSystem.IsWindows() ? ';' : ':';
foreach (var directory in pathVariable.Split(separator))
{
    ...
}
```

File: developer-cli/Utilities/ProcessHelper.cs [hunk 2]
```diff
@@ -123,6 +124,29 @@ public static bool IsProcessRunning(string process)
     {
         return Process.GetProcessesByName(process).Length > 0;
     }
+
+    private static string? FindFullPathFromPath(string command)
+    {
+        Debug.Assert(!string.IsNullOrWhiteSpace(command));
```
Comment (tjementum) [inline developer-cli/Utilities/ProcessHelper.cs:130]: Please remove this line. I don't use `Debug.Assert()` anywhere else, so for now, I prefer not to change this.

**Review by tjementum — CHANGES_REQUESTED** [review]
Hi Tiago

Thanks for the pull request, and sorry for the late reply. I get an exception on my Mac when running this, and I had to debug to find out what was wrong. It turns out this is because the PATH environment variable on Linux and macOS is split using `:` and not `;` like on Windows.

I made a comment and a suggested fix, but I will have to test that this did not break anything else. I don't have tests for the Developer CLI.

Also, I _always rebase branches_ before merging to main, and I _never merge main into a feature branch_. Please rebase your changes and squash everything, including my suggested change, into a single commit, and then force push the branch to your repository.

File: developer-cli/Utilities/ProcessHelper.cs [hunk 3]
```diff
@@ -123,6 +124,29 @@ public static bool IsProcessRunning(string process)
...
+
+        string[] commandFormats = OperatingSystem.IsWindows() ? ["{0}.exe", "{0}.cmd"] : ["{0}"];
```
Comment (tjementum) [inline developer-cli/Utilities/ProcessHelper.cs:132]:
```suggestion
        var commandFormats = OperatingSystem.IsWindows() ? new[] { "{0}.exe", "{0}.cmd" } : new[] { "{0}" };
```

You can run JetBrains code clean up and it will change `string[]` to `var`.

**Comment by thiagolunardi** [comment]
Hi @tjementum 

I can try adding a test project to it and putting together a workflow to test this functionality initially. I can run it on Windows, Linux, and Mac. For example, I can run `npm—v` and expect to get its version across all platforms.

```csharp
public static class ProcessHelperTests
{
    public class StartProcessTests 
    {
        [Theory]
        [InlineData("npm -v")
        public void RequestVersion_ShouldReturnValidSemver(string command)
        {
                // Act
                var output = ProcessHelper.StartProcess(
                    command,
                    redirectOutput: true,
                    throwOnError: true);

                // Assert
                Assert.True(Version.TryParse(output, out _));
        }
    }
}
``` 

For that, I will need to make a tiny move and change the directory structure to look like this:
```bash
.
.
├─ development-cli       # Contains the development CLI source code
│  ├─ cli                # A .NET CLI tool for automating common developer tasks
│  ├─ tests              # Tests for the CLI
```

Do you think it makes sense?

**Review by tjementum — APPROVED** [review]
I've made the requested changes and force pushed them.
